### ISSUE TITLE
Pretty date

### ISSUE THREAD

**Issue by easternbloc** [UKHomeOffice/passports-date-controller#1]
Allow pretty date to be set via options

**Comment by daniel-ac-martin** [comment]
There's a wider question over whether req.form[key + '-formatted'] should even exist. I created it in order to more closely mimic HOF's date-controller. (But the functionality could probably be moved into HOF if it is unwanted in HMPO tech.)

Possibly something nicer could be done using the formatters?

Perhaps it just shouldn't exist and code that wants nicely formatted dates should simple do their own formatting rather than expecting the date controller to have done it for them?

What do people think?

@gavboulton, @JoeChapman, @easternbloc, @joefitter, @oli-weighell2: Ping!

**Comment by joefitter** [comment]
Yeah, I agree we shouldn't be storing the formatted date this way, at least at the base controller level. IMO it should be down to the individual app to format the date

**Comment by gavboulton** [comment]
I'd say date formatting is a views thing. Template mixins has a date method which allows a custom format and defaults to 'D MMMM YYYY', https://github.com/UKHomeOffice/passports-template-mixins/blob/master/lib/template-mixins.js#L325-L331

**Comment by joefitter** [comment]
We could add a mustache lambda for displaying the formatted date, Ideally this would live in hof in a a shared partials folder or something

**Comment by joefitter** [comment]
ha - what he said ^

**Comment by daniel-ac-martin** [comment]
@gavboulton: Very nice. Sounds like we should be using that instead!

**Comment by easternbloc** [comment]
closing this as we can format the output using the mixins.
